### ISSUE TITLE
Email Address Field is currently only accepting inputs in all lower-case

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/fs-open-forest#48]
## Notes
A customer emailed the support team stating that they were unable to buy a permit because the email address field on the "buy permit" page (https://openforest.fs.usda.gov/christmas-trees/forests/arp/applications) was telling them they had an invalid address. Upon further investigation it was determined that the customer was using upper-case letters in their address. When we input the address with lower-case letters, everything functioned as normal.

## Tasks
- [ ] Test to see if issue can be replicated
- [ ] Update code to handle upper-case inputs
- [ ] PO approved

## Definition of Done
- [ ] The email field accepts inputs of upper and lower-case letters

**Comment by ASprinkle** [comment]
Story #1019 on the platform repo addressed this fix
