### ISSUE TITLE
As a Customer Support team member I would like some additional content added to the Support wiki, reflecting some of the new problems we've come across.

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/fs-open-forest#49]
## Notes
* What are things we should consider when making this story *

Over the last week, the Customer Support Team has had to field  several new issues. Namely:

- What to do when a Forest Service Employee cannot access certain admin features within the Open Forest platform
- What to tell a customer if they are attempting to use Internet Explorer to Access the site
- How to direct a customer if they are having trouble getting to the pay.gov site at the end of the permitting process

## Acceptance Criteria
- [ ] All three final drafts of the templates are loaded to the wiki
- [ ] @ASprinkle has given final approval

## Tasks
- [ ] Load draft for admin issues to Pinyon
- [ ] Load draft for Internet Explorer issues to Pinyon
- [ ] Load draft for pay.gov issues to pinyon
- [ ] Get the OK from Amber on all three templates
- [ ] Load all templates to the wiki

**Comment by ASprinkle** [comment]
I reviewed the templates. 

I made some edits directly into the wiki and I make some edits in the pinyon doc as well.

In the pinyon doc, I attempted to do the two-birds-one-stone thing and tweak it to cover “Accessing” pay.gov as well as “issues with pay.gov.” 
You can see in the pinyon doc versions that your original version is still V1… which you can still view and download.

Does that revision look ok to you? Do you think we’re missing anything?
