### ISSUE TITLE
As an Open Forest Admin I'd like to know that character limits in the Open Forest applications match the character limits in SUDS

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/fs-open-forest#63]
## Notes

It has come to our attention that certain applications in the Special-Use platform have not been able to be accepted to SUDS due to a restriction of 30 characters to certain fields in SUDS. However many applications seem to be accepted without any problem. We therefore need to determine which fields, exactly, have the character limit set on them and then take action to resolve this problem.

## Tasks
- [ ] Run multiple scenarios within the staging platform to determine which fields are not allowing more than 30 characters
- [ ] Determine if those fields really need to allow more than 30 characters
- [ ] Follow up with the SUDS team to determine if any problem fields can have there character limits expanded to match the character limits currently set in Open Forest
- [ ] Make another card to cover the steps needed to solve this problem depending on what the SUDS team is able to assist us with
- [ ] PO approved

## Definition of Done
- [ ] Fields that currently don't allow more than 30 characters are all identified
- [ ] Next steps to resolve the issue are in place in another card
